language: python
python:
- '3.6'
sudo: false
addons:
  ssh_known_hosts: daddytrapc.cn
before_install:
- echo "`date` - travis CI build"
install: echo "install"
before_script: echo "before_script"
script:
- echo "script"
after_failure: echo "after_failure"
after_success: echo "after_success"
before_deploy:
- openssl aes-256-cbc -k "$super_secret_password" -in deploy_rsa.enc -out /tmp/deploy_rsa -d
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
after_deploy: echo "after_deploy"
after_script: echo "after_script"
env:
  global:
    secure: FgxOslimf464EZqZejJf4OLka56L1kaBIH5+nLnCIkuHTWzw5tob3APihhy881KJM68Ox9IAxhgf+JjNyNW9C41Nnn4V9/LxN8hVGnjaiP9Pc/RHISyVG+kebP3TDYXZtA6Ewu8vIKvH3gLiPUDDNEbCEjqa+TiIyNNAJWBvq4+NGUTPt2YKh4dm1b2h/VlGLdz0D61grao+4wATgEgY/udbhhD3Pw8J/cYtXIe40bQCrB+YUHvE25Z6ge5+gg1PEtxoM5HOltVokWU0rdKIebgyijFTOmrE2/ioKQ1HOyAgiuSPIohBBr4hKEmdBdL3/V7mDfuvR8QcmqTxp0PfM0q6VXDguLikvvd33PgBmWoj5t+0Y7Z20rE19EHWWFHcnUL9MG3xWYyQwveferP9fq7US7bR41SJHj5rkxijRB0SnT4EPQ/jSP3BikRCQPPUfGQrNJ790D0D37/22ls9idE/x6y5n4agugtj0Nbagqs31l1wkhphPt1O8VJh7VX/gusWtVyRYqYY1rWV6Fzu+gmNsN6cDfwaIgGIy9ldlYFBZd7KRAjMjyTVpIh3eF+BUwQmxjMKiDRB3qhpHLsUGmVlUuggIg2cFwDhjf2s993/v2EprL/1aTIbpnRKWM4UpB0Mi0nDtmN/IFOm+mgvTjOIbUQ8J/7v5xdxkxW5qcs=
