language: python
sudo: false
before_install: echo "`date` - travis CI build"
install:
  - echo "install"
before_script: echo "before_script"
script:
  - echo "script"
after_failure: echo "after_failure"
after_success: echo "after_success"
before_deploy: echo "before_deploy"
deploy: true
after_deploy: echo "after_deploy"
after_script: echo "after_script"