language: python
python:
- '3.6'
sudo: false
addons:
  ssh_known_hosts: daddytrapc.cn
before_install:
- openssl aes-256-cbc -K $encrypted_a3ef82b692c4_key -iv $encrypted_a3ef82b692c4_iv
  -in deploy_rsa.enc -out deploy_rsa -d
- echo "`date` - travis CI build"
install: echo "install"
before_script: echo "before_script"
script:
- echo "script"
after_failure: echo "after_failure"
after_success: echo "after_success"
before_deploy:
- openssl aes-256-cbc -K $encrypted_a3ef82b692c4_key -iv $encrypted_a3ef82b692c4_iv
  -in deploy_rsa.enc -out deploy_rsa -d
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
after_deploy: echo "after_deploy"
after_script: echo "after_script"
